config/routes.rb
Rails.application.routes.draw do
  resources :thoughts
  devise_for :users
  root 'pages#home'

end

app/models/thought.rb
class Thought < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :thoughts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :set_thought, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
  end

  # GET /thoughts/new
  def new
    @thought = current_user.thoughts.build
  end

  # GET /thoughts/1/edit
  def edit
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = current_user.thoughts.build(thought_params)

    respond_to do |format|
      if @thought.save
        format.html { redirect_to @thought, notice: 'Thought was successfully created.' }
        format.json { render :show, status: :created, location: @thought }
      else
        format.html { render :new }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    respond_to do |format|
      if @thought.update(thought_params)
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought }
      else
        format.html { render :edit }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought.destroy
    respond_to do |format|
      format.html { redirect_to thoughts_url, notice: 'Thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      @thought = Thought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thought_params
      params.require(:thought).permit(:title, :body, :distress_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThoughtJournal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <h1>You are signed in</h1>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-lg" %>
<% else %>
  <h1>You aren't signed in</h1>
  <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
<% end %>

app/views/thoughts/_form.html.erb
<%= form_for(@thought) do |f| %>
  <% if @thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% @thought.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2>What would you like to call this entry?</h2>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <h2>How are you feeling? Write as much as you want (The more the better)</h2>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <h2>On a scale between 1-10(Incredibly Distressed - Not Distressed At All) how distressed are you?</h2>
    <%= f.number_field :distress_level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing Thought</h1>

<%= render 'form' %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Thoughts</h1>


    <% @thoughts.each do |thought| %>
         <%= thought.title %>
         <%= thought.body %>
         <%= thought.distress_level %>
         <%= thought.user.email %> 
         <%= link_to 'Show', thought %>
         <%= link_to 'Edit', edit_thought_path(thought) %>
         <%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
<br>

<%= link_to 'New Thought', new_thought_path %>

app/views/thoughts/new.html.erb
<h1>New Thought</h1>

<%= render 'form' %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @thought.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @thought.body %>
</p>

<p>
  <strong>Distress level:</strong>
  <%= @thought.distress_level %>
</p>

<p>
  <strong>User:</strong>
  <%= @thought.user.email %>
</p>

<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>